
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY no4_x4 IS
PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
);
END no4_x4;

ARCHITECTURE RTL OF no4_x4 IS
BEGIN
  nq <= NOT((((i0 OR i1) OR i2) OR i3));
END RTL;
