.TH "anonymous_namespace{TrackElement.cpp}" 3 "Sun Nov 21 2021" "Version 1.0" "Kite - Detailed Router" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anonymous_namespace{TrackElement.cpp}
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Kite - Detailed Router from the source code\&.
