.TH "grpSynthHierarchy" 3 "Fri Oct 1 2021" "Version 1.0" "Kite - Detailed Router" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grpSynthHierarchy \- Simplificated class hierarchy\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Simplificated class hierarchy\&. 

 
.SH "Author"
.PP 
Generated automatically by Doxygen for Kite - Detailed Router from the source code\&.
