.TH "VerticalTrack" 3 "Thu Nov 12 2020" "Version 1.0" "Kite - Detailed Router" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VerticalTrack \- Vertical track managment\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTrack\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBisHorizontal\fP () const"
.br
.ti -1c
.RI "virtual bool \fBisVertical\fP () const"
.br
.ti -1c
.RI "virtual unsigned int \fBgetDirection\fP () const"
.br
.ti -1c
.RI "virtual \fBPoint\fP \fBgetPosition\fP (\fBDbU::Unit\fP coordinate) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Vertical track managment\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool isHorizontal () const\fC [virtual]\fP"
\fBReturns:\fP \fBtrue\fP if the \fBTrack\fP in horizontal direction\&. 
.PP
Implements \fBTrack\fP\&.
.SS "bool isVertical () const\fC [virtual]\fP"
\fBReturns:\fP \fBfalse\fP\&.
.PP
\fBReturns:\fP \fBtrue\fP\&. 
.PP
Implements \fBTrack\fP\&.
.SS "unsigned int getDirection () const\fC [virtual]\fP"
\fBReturns:\fP Katabatic::KbVertical\&. 
.PP
Implements \fBTrack\fP\&.
.SS "\fBPoint\fP getPosition (\fBDbU::Unit\fP position) const\fC [virtual]\fP"
\fBReturns:\fP the point at \fC\fP(\fBgetAxis()\fP,position)\&. 
.PP
Implements \fBTrack\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Kite - Detailed Router from the source code\&.
