FROM quay.io/pypa/manylinux_2_28

RUN yum -y install epel-release
#ADD https://ftp.lip6.fr/lip6/softs/coriolis/etc/epel-7/epel.repo          /etc/yum.repo.d/
#ADD https://ftp.lip6.fr/lip6/softs/coriolis/etc/epel-7/RPM-GPG-KEY-EPEL-7 /etc/pki/rpm-gpg/
RUN yum repolist

RUN yum install -y \
 ccache            \
 bison             \
 flex              \
 flex-devel        \
 boost-devel       \
 bzip2-devel       \
 libxml2-devel     \
 rapidjson-devel   \
 eigen3-devel      \
 qt5-qtbase-devel  \
 qt5-qtsvg-devel   \
 qwt-qt5-devel     \
 doxygen           \
 wget
