FROM quay.io/pypa/manylinux2014_x86_64:2023-07-14-55e4124

RUN yum -y install epel-release && \
 yum repolist

RUN yum install -y \
 qt5-qtbase-devel qt5-qtsvg-devel \
 rapidjson-devel bison flex doxygen bzip2-devel flex-devel \
 boost169-devel \
 python36-devel libxml2-devel \
 qwt-devel \
 ccache \
 eigen3-devel \
 wget

RUN wget http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz;
RUN tar -xzf lemon-1.3.1.tar.gz; cd lemon-1.3.1; mkdir build; cd build; cmake ..; make install; cd ../..

