

// This file is part of the Coriolis Project.
// Copyright (C) Laboratoire LIP6 - Departement ASIM
// Universite Pierre et Marie Curie
//
// Main contributors :
//        Christophe Alexandre   <Christophe.Alexandre@lip6.fr>
//        Sophie Belloeil             <Sophie.Belloeil@lip6.fr>
//        Hugo Clément                   <Hugo.Clement@lip6.fr>
//        Jean-Paul Chaput           <Jean-Paul.Chaput@lip6.fr>
//        Damien Dupuis                 <Damien.Dupuis@lip6.fr>
//        Christian Masson           <Christian.Masson@lip6.fr>
//        Marek Sroka                     <Marek.Sroka@lip6.fr>
// 
// The  Coriolis Project  is  free software;  you  can redistribute it
// and/or modify it under the  terms of the GNU General Public License
// as published by  the Free Software Foundation; either  version 2 of
// the License, or (at your option) any later version.
// 
// The  Coriolis Project is  distributed in  the hope that it  will be
// useful, but WITHOUT ANY WARRANTY; without even the implied warranty
// of MERCHANTABILITY  or FITNESS FOR  A PARTICULAR PURPOSE.   See the
// GNU General Public License for more details.
// 
// You should have  received a copy of the  GNU General Public License
// along with the Coriolis Project; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
// USA
//
// License-Tag
// Authors-Tag
// ===================================================================
// -*- C++ -*-
//
// $Id: UnknownBoldNormal14.h,v 1.3 2006/02/19 00:52:42 jpc Exp $
//
// x-----------------------------------------------------------------x 
// |                                                                 |
// |                   C O R I O L I S                               |
// |          Alliance / Hurricane  Interface                        |
// |                                                                 |
// |  Author      :                    Jean-Paul CHAPUT              |
// |  E-mail      :       Jean-Paul.Chaput@asim.lip6.fr              |
// | =============================================================== |
// |  C++ Header  :       "./UnknownBoldNormal14.h"                  |
// | *************************************************************** |
// |                                                                 |
// |  Rights on font material :                                      |
// |    Donated by H. Kagotani <kagotani@cs.titech.ac.jp>. Public    |
// |  domain font from Japan.                                        |
// |                                                                 |
// | -Misc-Fixed-Medium-R-Normal--14-130-75-75-C-140-JISX0208.1983-0 |
// |             "Public domain font. Share and enjoy."              |
// |                                                                 |
// |    This font has been extracted from X11r5 bdf file by          |
// |  Frédéric Pétrot <Frederic.Petrot@lip6.fr>, to be used for the  |
// |  standard Alliance CAD system banners, and kept for Coriolis.   |
// |                                                                 |
// |  Character set :                                                |
// |    0123456789abcdefghijklmnopqrtuvwxyz                          |
// |              ABCDEFGHIJKLMOPQRSTUVWXYZ                          |
// |                                                                 |
// | =============================================================== |
// |  U p d a t e s                                                  |
// |                                                                 |
// x-----------------------------------------------------------------x


const char *Unknown_Bold_Normal_14_0[15] = { "         "
                                           , "   @@@   "
                                           , " @@   @@ "
                                           , "@@     @@"
                                           , "@@     @@"
                                           , "@@     @@"
                                           , "@@     @@"
                                           , "@@     @@"
                                           , "@@     @@"
                                           , "@@     @@"
                                           , " @@   @@ "
                                           , "   @@@   "
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_1[15] = { "      "
                                           , "   @  "
                                           , "  @@  "
                                           , "@@@@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "@@@@@@"
                                           , "      "
                                           , "      "
                                           , "      " };

const char *Unknown_Bold_Normal_14_2[15] = { "        "
                                           , "  @@@@  "
                                           , " @   @@ "
                                           , "@@    @@"
                                           , "@@@   @@"
                                           , " @   @@ "
                                           , "     @  "
                                           , "    @   "
                                           , "   @    "
                                           , "  @    @"
                                           , " @@@@@@ "
                                           , "@@@@@@@ "
                                           , "        "
                                           , "        "
                                           , "        " };

const char *Unknown_Bold_Normal_14_3[15] = { "        "
                                           , "  @@@@  "
                                           , " @   @@ "
                                           , "@@    @@"
                                           , "@@    @@"
                                           , "     @@ "
                                           , "   @@@  "
                                           , "      @ "
                                           , "@@    @@"
                                           , "@@    @@"
                                           , " @   @@ "
                                           , "  @@@@  "
                                           , "        "
                                           , "        "
                                           , "        " };

const char *Unknown_Bold_Normal_14_4[15] = { "         "
                                           , "     @@  "
                                           , "    @@@  "
                                           , "   @ @@  "
                                           , "   @ @@  "
                                           , "  @  @@  "
                                           , " @   @@  "
                                           , "@@   @@  "
                                           , "@@@@@@@@@"
                                           , "     @@  "
                                           , "     @@  "
                                           , "    @@@@ "
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_5[15] = { "        "
                                           , " @@@@@@@"
                                           , " @@@@@@ "
                                           , " @      "
                                           , " @      "
                                           , " @@@@@  "
                                           , "     @@ "
                                           , "      @@"
                                           , "      @@"
                                           , "@@    @@"
                                           , "@@   @@ "
                                           , " @@@@   "
                                           , "        "
                                           , "        "
                                           , "        " };

const char *Unknown_Bold_Normal_14_6[15] = { "         "
                                           , "   @@@@  "
                                           , "  @   @@ "
                                           , " @@   @@ "
                                           , " @       "
                                           , "@@ @@@@  "
                                           , "@@@   @@ "
                                           , "@@     @@"
                                           , "@@     @@"
                                           , "@@     @@"
                                           , " @@   @@ "
                                           , "   @@@   "
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_7[15] = { "         "
                                           , " @@@@@@@@"
                                           , " @@@@@@@ "
                                           , "@     @  "
                                           , "     @   "
                                           , "     @   "
                                           , "    @    "
                                           , "    @    "
                                           , "   @@    "
                                           , "   @@    "
                                           , "   @@    "
                                           , "   @@    "
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_8[15] = { "        "
                                           , "  @@@@  "
                                           , " @    @ "
                                           , "@@    @@"
                                           , "@@@   @@"
                                           , " @@@ @@ "
                                           , "  @@@@  "
                                           , " @@ @@@ "
                                           , "@@   @@@"
                                           , "@@    @@"
                                           , " @    @ "
                                           , "  @@@@  "
                                           , "        "
                                           , "        "
                                           , "        " };

const char *Unknown_Bold_Normal_14_9[15] = { "        "
                                           , "   @@   "
                                           , " @@  @@ "
                                           , "@@    @@"
                                           , "@@    @@"
                                           , "@@    @@"
                                           , " @@  @@@"
                                           , "  @@@ @@"
                                           , "      @@"
                                           , "@@    @ "
                                           , "@@   @  "
                                           , " @@@@   "
                                           , "        "
                                           , "        "
                                           , "        " };

const char *Unknown_Bold_Normal_14_A[15] = { "            "
                                           , "      @     "
                                           , "      @     "
                                           , "     @@@    "
                                           , "     @@@    "
                                           , "    @  @@   "
                                           , "    @  @@   "
                                           , "   @    @@  "
                                           , "   @@@@@@@  "
                                           , "  @      @@ "
                                           , "  @      @@ "
                                           , "@@@@    @@@@"
                                           , "            "
                                           , "            "
                                           , "            " };

const char *Unknown_Bold_Normal_14_B[15] = { "           "
                                           , "@@@@@@@    "
                                           , "  @@   @@  "
                                           , "  @@    @@ "
                                           , "  @@    @@ "
                                           , "  @@   @@  "
                                           , "  @@@@@@   "
                                           , "  @@    @@ "
                                           , "  @@     @@"
                                           , "  @@     @@"
                                           , "  @@    @@ "
                                           , "@@@@@@@@   "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_C[15] = { "          "
                                           , "    @@@@ @"
                                           , "  @@    @@"
                                           , " @@      @"
                                           , "@@       @"
                                           , "@@        "
                                           , "@@        "
                                           , "@@        "
                                           , "@@        "
                                           , " @@      @"
                                           , "  @@    @@"
                                           , "    @@@@  "
                                           , "          "
                                           , "          "
                                           , "          " };

const char *Unknown_Bold_Normal_14_D[15] = { "           "
                                           , "@@@@@@@    "
                                           , "  @@   @@  "
                                           , "  @@    @@ "
                                           , "  @@     @@"
                                           , "  @@     @@"
                                           , "  @@     @@"
                                           , "  @@     @@"
                                           , "  @@     @@"
                                           , "  @@    @@ "
                                           , "  @@   @@  "
                                           , "@@@@@@@    "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_E[15] = { "           "
                                           , "@@@@@@@@@  "
                                           , "  @@    @  "
                                           , "  @@     @ "
                                           , "  @@       "
                                           , "  @@   @   "
                                           , "  @@@@@@   "
                                           , "  @@   @   "
                                           , "  @@       "
                                           , "  @@      @"
                                           , "  @@     @ "
                                           , "@@@@@@@@@@ "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_F[15] = { "          "
                                           , "@@@@@@@@@ "
                                           , "  @@    @ "
                                           , "  @@     @"
                                           , "  @@      "
                                           , "  @@   @  "
                                           , "  @@@@@@  "
                                           , "  @@   @  "
                                           , "  @@      "
                                           , "  @@      "
                                           , "  @@      "
                                           , "@@@@@@    "
                                           , "          "
                                           , "          "
                                           , "          " };

const char *Unknown_Bold_Normal_14_G[15] = { "            "
                                           , "    @@@@ @  "
                                           , "  @@    @@  "
                                           , " @@      @  "
                                           , "@@          "
                                           , "@@          "
                                           , "@@     @@@@@"
                                           , "@@     @ @@ "
                                           , "@@    @  @@ "
                                           , " @@      @@ "
                                           , "  @@    @@  "
                                           , "    @@@@    "
                                           , "            "
                                           , "            "
                                           , "            " };

const char *Unknown_Bold_Normal_14_H[15] = { "           "
                                           , "@@@@   @@@@"
                                           , " @@     @@ "
                                           , " @@     @@ "
                                           , " @@     @@ "
                                           , " @@     @@ "
                                           , " @@@@@@@@@ "
                                           , " @@     @@ "
                                           , " @@     @@ "
                                           , " @@     @@ "
                                           , " @@     @@ "
                                           , "@@@@   @@@@"
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_I[15] = { "      "
                                           , "@@@@@@"
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "@@@@@@"
                                           , "      "
                                           , "      "
                                           , "      " };

const char *Unknown_Bold_Normal_14_J[15] = { "           "
                                           , "     @@@@@@"
                                           , "       @@  "
                                           , "       @@  "
                                           , "       @@  "
                                           , "       @@  "
                                           , "       @@  "
                                           , " @     @@  "
                                           , "@@@    @@  "
                                           , "@@     @@  "
                                           , " @@   @@   "
                                           , "   @@@     "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_K[15] = { "           "
                                           , "@@@@   @@@@"
                                           , " @@     @  "
                                           , " @@    @   "
                                           , " @@   @    "
                                           , " @@  @@    "
                                           , " @@ @ @@   "
                                           , " @@@  @@   "
                                           , " @@    @@  "
                                           , " @@    @@  "
                                           , " @@     @@ "
                                           , "@@@@   @@@@"
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_L[15] = { "           "
                                           , "@@@@@@     "
                                           , "  @@       "
                                           , "  @@       "
                                           , "  @@       "
                                           , "  @@       "
                                           , "  @@       "
                                           , "  @@       "
                                           , "  @@       "
                                           , "  @@      @"
                                           , "  @@     @ "
                                           , "@@@@@@@@@@ "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_M[15] = { "           "
                                           , "@@@     @@@"
                                           , " @@     @@ "
                                           , " @@@   @@@ "
                                           , " @@@   @@@ "
                                           , " @ @@ @ @@ "
                                           , " @ @@ @ @@ "
                                           , " @ @@@  @@ "
                                           , " @  @@  @@ "
                                           , " @  @   @@ "
                                           , " @      @@ "
                                           , "@@@    @@@@"
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_N[15] = { "          "
                                           , "@@@    @@@"
                                           , " @@     @ "
                                           , " @@@    @ "
                                           , " @ @@   @ "
                                           , " @ @@   @ "
                                           , " @  @@  @ "
                                           , " @   @@ @ "
                                           , " @   @@ @ "
                                           , " @    @@@ "
                                           , " @     @@ "
                                           , "@@@    @@ "
                                           , "          "
                                           , "          "
                                           , "          " };

const char *Unknown_Bold_Normal_14_O[15] = { "           "
                                           , "    @@@    "
                                           , "  @@   @@  "
                                           , " @@     @@ "
                                           , "@@       @@"
                                           , "@@       @@"
                                           , "@@       @@"
                                           , "@@       @@"
                                           , "@@       @@"
                                           , " @@     @@ "
                                           , "  @@   @@  "
                                           , "    @@@    "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_P[15] = { "          "
                                           , "@@@@@@@   "
                                           , "  @@   @@ "
                                           , "  @@    @@"
                                           , "  @@    @@"
                                           , "  @@   @@ "
                                           , "  @@@@@   "
                                           , "  @@      "
                                           , "  @@      "
                                           , "  @@      "
                                           , "  @@      "
                                           , "@@@@@@    "
                                           , "          "
                                           , "          "
                                           , "          " };

const char *Unknown_Bold_Normal_14_Q[15] = { "           "
                                           , "    @@@    "
                                           , "  @@   @@  "
                                           , " @@     @@ "
                                           , "@@       @@"
                                           , "@@       @@"
                                           , "@@       @@"
                                           , "@@       @@"
                                           , "@@  @@   @@"
                                           , " @@@  @ @@ "
                                           , "  @@   @@  "
                                           , "    @@@@@  "
                                           , "         @@"
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_R[15] = { "           "
                                           , "@@@@@@@    "
                                           , "  @@   @@  "
                                           , "  @@    @@ "
                                           , "  @@    @@ "
                                           , "  @@   @@  "
                                           , "  @@@@@    "
                                           , "  @@  @@   "
                                           , "  @@   @@  "
                                           , "  @@   @@  "
                                           , "  @@    @@ "
                                           , "@@@@@   @@@"
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_S[15] = { "         "
                                           , "  @@@@ @ "
                                           , " @    @@ "
                                           , "@@     @ "
                                           , "@@@      "
                                           , " @@@@    "
                                           , "   @@@@  "
                                           , "     @@@ "
                                           , "@      @@"
                                           , "@@     @@"
                                           , "@@@    @ "
                                           , "@  @@@@  "
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_T[15] = { "            "
                                           , " @@@@@@@@@@ "
                                           , " @   @@   @ "
                                           , "@    @@    @"
                                           , "     @@     "
                                           , "     @@     "
                                           , "     @@     "
                                           , "     @@     "
                                           , "     @@     "
                                           , "     @@     "
                                           , "     @@     "
                                           , "   @@@@@@   "
                                           , "            "
                                           , "            "
                                           , "            " };

const char *Unknown_Bold_Normal_14_U[15] = { "           "
                                           , "@@@@    @@@"
                                           , " @@      @ "
                                           , " @@      @ "
                                           , " @@      @ "
                                           , " @@      @ "
                                           , " @@      @ "
                                           , " @@      @ "
                                           , " @@      @ "
                                           , " @@      @ "
                                           , "  @@    @  "
                                           , "    @@@@   "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_V[15] = { "           "
                                           , "@@@@    @@@"
                                           , " @@      @ "
                                           , " @@      @ "
                                           , "  @@    @  "
                                           , "  @@    @  "
                                           , "   @@  @   "
                                           , "   @@  @   "
                                           , "    @@@    "
                                           , "    @@@    "
                                           , "     @     "
                                           , "     @     "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_W[15] = { "           "
                                           , "@@@ @@@ @@@"
                                           , " @@  @@  @ "
                                           , " @@  @@  @ "
                                           , " @@  @@  @ "
                                           , "  @@ @@@ @ "
                                           , "  @@@ @@@  "
                                           , "  @@@ @@@  "
                                           , "   @@  @@  "
                                           , "   @@  @@  "
                                           , "   @@  @@  "
                                           , "   @@  @@  "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_X[15] = { "           "
                                           , "@@@@   @@@@"
                                           , " @@     @  "
                                           , "  @@   @   "
                                           , "   @@ @    "
                                           , "    @@     "
                                           , "    @@     "
                                           , "    @@@    "
                                           , "   @  @@   "
                                           , "  @    @@  "
                                           , " @      @@ "
                                           , "@@@    @@@@"
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_Y[15] = { "           "
                                           , "@@@@   @@@@"
                                           , " @@     @  "
                                           , "  @@   @   "
                                           , "   @@ @    "
                                           , "    @@     "
                                           , "    @@     "
                                           , "    @@     "
                                           , "    @@     "
                                           , "    @@     "
                                           , "    @@     "
                                           , "  @@@@@@   "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_Z[15] = { "           "
                                           , " @@@@@@@@@ "
                                           , " @     @@  "
                                           , "@     @@   "
                                           , "     @@    "
                                           , "     @@    "
                                           , "    @@     "
                                           , "   @@      "
                                           , "   @@      "
                                           , "  @@      @"
                                           , " @@      @ "
                                           , "@@@@@@@@@@ "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_a[15] = { "         "
                                           , "         "
                                           , "         "
                                           , "         "
                                           , "  @@@@   "
                                           , " @@   @  "
                                           , " @@   @@ "
                                           , "   @@@@@ "
                                           , " @@   @@ "
                                           , "@@    @@ "
                                           , "@@   @@@ "
                                           , " @@@@  @@"
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_b[15] = { "         "
                                           , "@@@      "
                                           , " @@      "
                                           , " @@      "
                                           , " @@ @@   "
                                           , " @@@  @@ "
                                           , " @@    @@"
                                           , " @@    @@"
                                           , " @@    @@"
                                           , " @@    @@"
                                           , " @@@  @@ "
                                           , "@@@ @@   "
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_c[15] = { "        "
                                           , "        "
                                           , "        "
                                           , "        "
                                           , "   @@@  "
                                           , " @@   @@"
                                           , "@@     @"
                                           , "@@      "
                                           , "@@      "
                                           , "@@     @"
                                           , " @@   @@"
                                           , "   @@@  "
                                           , "        "
                                           , "        "
                                           , "        " };

const char *Unknown_Bold_Normal_14_d[15] = { "         "
                                           , "     @@@ "
                                           , "      @@ "
                                           , "      @@ "
                                           , "   @@ @@ "
                                           , " @@  @@@ "
                                           , "@@    @@ "
                                           , "@@    @@ "
                                           , "@@    @@ "
                                           , "@@    @@ "
                                           , " @@  @@@ "
                                           , "   @@ @@@"
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_e[15] = { "         "
                                           , "         "
                                           , "         "
                                           , "         "
                                           , "  @@@@@  "
                                           , " @     @ "
                                           , "@@     @@"
                                           , "@@@@@@@@@"
                                           , "@@       "
                                           , "@@      @"
                                           , " @@    @@"
                                           , "   @@@@  "
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_f[15] = { "        "
                                           , "    @@@ "
                                           , "   @  @@"
                                           , "  @@  @@"
                                           , "  @@    "
                                           , "@@@@@@@@"
                                           , "  @@    "
                                           , "  @@    "
                                           , "  @@    "
                                           , "  @@    "
                                           , "  @@    "
                                           , "@@@@@@  "
                                           , "        "
                                           , "        "
                                           , "        " };

const char *Unknown_Bold_Normal_14_g[15] = { "        "
                                           , "        "
                                           , "        "
                                           , "        "
                                           , "  @@@@@@"
                                           , " @@  @@ "
                                           , " @   @@ "
                                           , " @   @  "
                                           , "  @@@   "
                                           , " @@     "
                                           , " @@@@@@ "
                                           , "@@   @@@"
                                           , " @     @"
                                           , "  @@@@@ "
                                           , "        " };

const char *Unknown_Bold_Normal_14_h[15] = { "          "
                                           , "@@@       "
                                           , " @@       "
                                           , " @@       "
                                           , " @@ @@@   "
                                           , " @@@  @@  "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , "@@@@  @@@@"
                                           , "          "
                                           , "          "
                                           , "          " };

const char *Unknown_Bold_Normal_14_i[15] = { "      "
                                           , "   @  "
                                           , "  @@@ "
                                           , "   @  "
                                           , "      "
                                           , "@@@@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "@@@@@@"
                                           , "      "
                                           , "      "
                                           , "      " };

const char *Unknown_Bold_Normal_14_j[15] = { "      "
                                           , "    @ "
                                           , "   @@@"
                                           , "    @ "
                                           , "      "
                                           , " @@@@@"
                                           , "    @@"
                                           , "    @@"
                                           , "    @@"
                                           , "    @@"
                                           , "    @@"
                                           , "@@  @@"
                                           , "@@  @ "
                                           , " @@@  "
                                           , "      " };

const char *Unknown_Bold_Normal_14_k[15] = { "          "
                                           , "@@@       "
                                           , " @@       "
                                           , " @@   @@@ "
                                           , " @@   @   "
                                           , " @@  @    "
                                           , " @@ @@@   "
                                           , " @@@ @@   "
                                           , " @@   @@  "
                                           , " @@   @@  "
                                           , " @@    @@ "
                                           , "@@@@   @@@"
                                           , "          "
                                           , "          "
                                           , "          " };

const char *Unknown_Bold_Normal_14_l[15] = { "      "
                                           , "@@@@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "  @@  "
                                           , "@@@@@@"
                                           , "      "
                                           , "      "
                                           , "      " };

const char *Unknown_Bold_Normal_14_m[15] = { "            "
                                           , "            "
                                           , "            "
                                           , "            "
                                           , "@@@ @@ @@@  "
                                           , " @@@ @@  @@ "
                                           , " @@  @@  @@ "
                                           , " @@  @@  @@ "
                                           , " @@  @@  @@ "
                                           , " @@  @@  @@ "
                                           , " @@  @@  @@ "
                                           , "@@@@ @@@ @@@"
                                           , "            "
                                           , "            "
                                           , "            " };

const char *Unknown_Bold_Normal_14_n[15] = { "          "
                                           , "          "
                                           , "          "
                                           , "          "
                                           , "@@@ @@@   "
                                           , " @@@   @  "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , "@@@@  @@@@"
                                           , "          "
                                           , "          "
                                           , "          " };

const char *Unknown_Bold_Normal_14_o[15] = { "         "
                                           , "         "
                                           , "         "
                                           , "         "
                                           , "   @@@   "
                                           , " @@   @@ "
                                           , "@@     @@"
                                           , "@@     @@"
                                           , "@@     @@"
                                           , "@@     @@"
                                           , " @@   @@ "
                                           , "   @@@   "
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_p[15] = { "         "
                                           , "         "
                                           , "         "
                                           , "         "
                                           , "@@@ @@@  "
                                           , " @@@  @@ "
                                           , " @@    @@"
                                           , " @@    @@"
                                           , " @@    @@"
                                           , " @@    @@"
                                           , " @@@  @@ "
                                           , " @@ @@@  "
                                           , " @@      "
                                           , "@@@@     "
                                           , "         " };

const char *Unknown_Bold_Normal_14_q[15] = { "         "
                                           , "         "
                                           , "         "
                                           , "         "
                                           , "  @@@ @@@"
                                           , " @@  @@@ "
                                           , "@@    @@ "
                                           , "@@    @@ "
                                           , "@@    @@ "
                                           , "@@    @@ "
                                           , " @@  @@@ "
                                           , "  @@@ @@ "
                                           , "      @@ "
                                           , "     @@@@"
                                           , "         " };

const char *Unknown_Bold_Normal_14_r[15] = { "        "
                                           , "        "
                                           , "        "
                                           , "        "
                                           , "@@@ @@@ "
                                           , " @@@  @@"
                                           , " @@   @@"
                                           , " @@     "
                                           , " @@     "
                                           , " @@     "
                                           , " @@     "
                                           , "@@@@    "
                                           , "        "
                                           , "        "
                                           , "        " };

const char *Unknown_Bold_Normal_14_s[15] = { "        "
                                           , "        "
                                           , "        "
                                           , "        "
                                           , " @@@@@@ "
                                           , "@@    @ "
                                           , "@@@     "
                                           , " @@@@   "
                                           , "   @@@@ "
                                           , "@    @@@"
                                           , "@@    @@"
                                           , "@ @@@@@ "
                                           , "        "
                                           , "        "
                                           , "        " };

const char *Unknown_Bold_Normal_14_t[15] = { "        "
                                           , "        "
                                           , "   @    "
                                           , "  @@    "
                                           , "  @@    "
                                           , "@@@@@@@@"
                                           , "  @@    "
                                           , "  @@    "
                                           , "  @@    "
                                           , "  @@    "
                                           , "  @@   @"
                                           , "   @@@@ "
                                           , "        "
                                           , "        "
                                           , "        " };
const char *Unknown_Bold_Normal_14_u[15] = { "          "
                                           , "          "
                                           , "          "
                                           , "          "
                                           , "@@@  @@@@ "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , " @@    @@ "
                                           , " @@   @@@ "
                                           , "  @@@@  @@"
                                           , "          "
                                           , "          "
                                           , "          " };

const char *Unknown_Bold_Normal_14_v[15] = { "          "
                                           , "          "
                                           , "          "
                                           , "          "
                                           , "@@@@@  @@@"
                                           , " @@     @ "
                                           , "  @@   @  "
                                           , "  @@   @  "
                                           , "   @@ @   "
                                           , "   @@ @   "
                                           , "    @@    "
                                           , "    @@    "
                                           , "          "
                                           , "          "
                                           , "          " };

const char *Unknown_Bold_Normal_14_w[15] = { "           "
                                           , "           "
                                           , "           "
                                           , "           "
                                           , "@@@@ @@ @@@"
                                           , " @@  @@  @ "
                                           , " @@  @@  @ "
                                           , "  @@@ @@ @ "
                                           , "  @@@ @@@  "
                                           , "   @@  @@  "
                                           , "   @@  @@  "
                                           , "   @@  @@  "
                                           , "           "
                                           , "           "
                                           , "           " };

const char *Unknown_Bold_Normal_14_x[15] = { "         "
                                           , "         "
                                           , "         "
                                           , "         "
                                           , "@@@@  @@@"
                                           , " @@    @ "
                                           , "  @@  @  "
                                           , "   @@@   "
                                           , "   @@@   "
                                           , "  @  @@  "
                                           , " @    @@ "
                                           , "@@@  @@@@"
                                           , "         "
                                           , "         "
                                           , "         " };

const char *Unknown_Bold_Normal_14_y[15] = { "         "
                                           , "         "
                                           , "         "
                                           , "         "
                                           , "@@@@@ @@@"
                                           , " @@    @ "
                                           , "  @@   @ "
                                           , "  @@  @  "
                                           , "   @@ @  "
                                           , "   @@@   "
                                           , "    @@   "
                                           , "@@  @    "
                                           , "@@  @    "
                                           , " @@@     "
                                           , "         " };

const char *Unknown_Bold_Normal_14_z[15] = { "        "
                                           , "        "
                                           , "        "
                                           , "        "
                                           , "@@@@@@@@"
                                           , "@    @@ "
                                           , "    @@  "
                                           , "   @@   "
                                           , "  @@    "
                                           , " @@     "
                                           , "@@     @"
                                           , "@@@@@@@@"
                                           , "        "
                                           , "        "
                                           , "        " };
