Hurricane::Net Class Reference
Net description (API)
Classes
class Direction
class Type
Public Types
typedef Entity Inherit
typedef unsigned Arity
Public Member Functions
const Name & getName () const
const Arity & getArity () const
const Type & getType () const
const Direction & getDirection () const
const Point & getPosition () const
const DbU::Unit & getX () const
const DbU::Unit & getY () const
Components getComponents () const
Rubbers getRubbers () const
RoutingPads getRoutingPads () const
Plugs getPlugs () const
Contacts getContacts () const
Segments getSegments () const
Verticals getVerticals () const
Horizontals getHorizontals () const
Pads getPads () const
Plugs getSlavePlugs () const
Plugs getConnectedSlavePlugs () const
Plugs getUnconnectedSlavePlugs () const
bool isGlobal () const
bool isExternal () const
bool isLogical () const
bool isClock () const
bool isSupply () const
void setName (Name name)
void setArity (const Arity &arity)
void setGlobal (bool isGlobal)
void setExternal (bool isExternal)
void setType (const Type &type)
void setDirection (const Direction &direction)
void setPosition (const Point &position)
void materialize ()
void unmaterialize ()
void merge (Net *net)
Net * getClone (Cell *cloneCell)
Static Public Member Functions
static Net * create (Cell *cell, const Name &name)
static NetFilter getIsGlobalFilter ()
static NetFilter getIsExternalFilter ()
static NetFilter getIsInternalFilter ()
static NetFilter getIsClockFilter ()
static NetFilter getIsSupplyFilter ()
Detailed Description
Net description (API)
Predefined filters
Hurricane::Net::getIsGlobalFilter
Hurricane::Net::getIsExternalFilter
Hurricane::Net::getIsInternalFilter
Hurricane::Net::getIsClockFilter
Hurricane::Net::getIsSupplyFilter
Member Typedef Documentation
Inherit
Hurricane::Net::Inherit
Useful for calling upon methods of the base class without knowing it.
Arity
Hurricane::Net::Arity
This type allows to represent the number of bits associated to a net (a null value meaning undefined).
Member Function Documentation
create()
Net * Hurricane::Net::create (Cell * cell, const Name & name) [static]
Creates and returns a new net named <name> for the cell <cell>.
Caution:
Throws an exception if the cell is null, if the name empty or if a net with same name already exists.
getName()
const Name & Hurricane::Net::getName () const [inline]
Returns: the net name.
Referenced by isSupply().
getArity()
const Net::Arity & Hurricane::Net::getArity () const [inline]
Returns: the signal arity (by default set to 1).
getType()
const Net::Type & Hurricane::Net::getType () const [inline]
Returns: the signal type (by default set to UNDEFINED).
getDirection()
const Net::Direction & Hurricane::Net::getDirection () const [inline]
Returns: the signal direction (by default set to UNDEFINED).
Remark:
This direction is meaningfull only for external nets.
getPosition()
const Point & Hurricane::Net::getPosition () const [inline]
Returns: the X,Y position of the net. This position is used for computing the location of the plugs (on slave instances calling the cell owning this net) having that net as master.
getX()
const Unit & Hurricane::Net::getX () const [inline]
Returns: net abscissa.
getY()
const Unit & Hurricane::Net::getY () const [inline]
Returns: net ordinate.
getComponents()
Components Hurricane::Net::getComponents () const [inline]
Returns: the collection of net's components.
getRubbers()
Rubbers Hurricane::Net::getRubbers () const [inline]
Returns: the collection of net's rubbers.
References getConnectedSlavePlugs(), getContacts(), getHorizontals(), getIsClockFilter(), getIsExternalFilter(), getIsGlobalFilter(), getIsInternalFilter(), getIsSupplyFilter(), getPads(), getPlugs(), getRoutingPads(), getSegments(), getSlavePlugs(), getUnconnectedSlavePlugs(), and getVerticals().
getRoutingPads()
RoutingPads Hurricane::Net::getRoutingPads () const
Returns: the collection of net's RoutingPads.
Referenced by getRubbers().
getPlugs()
Plugs Hurricane::Net::getPlugs () const
Returns: the collection of net's plugs.
Referenced by getRubbers().
getContacts()
Contacts Hurricane::Net::getContacts () const
Returns: the collection of net's contacts.
Referenced by getRubbers().
getSegments()
Segments Hurricane::Net::getSegments () const
Returns: the collection of net's segments.
Referenced by getRubbers().
getVerticals()
Verticals Hurricane::Net::getVerticals () const
Returns: the collection of net's vertical segments.
Referenced by getRubbers().
getHorizontals()
Horizontals Hurricane::Net::getHorizontals () const
Returns: the collection of net's horizontal segments.
Referenced by getRubbers().
getPads()
Pads Hurricane::Net::getPads () const
Returns: the collection of net's pads.
Referenced by getRubbers().
getSlavePlugs()
Plugs Hurricane::Net::getSlavePlugs () const
Returns: the collection of plugs which have this net as master.
Remark:
Meaningfull only for external nets.
Referenced by getRubbers().
getConnectedSlavePlugs()
Plugs Hurricane::Net::getConnectedSlavePlugs () const
Returns: the collection of connected plugs which have this net as master.
Remark:
Meaningfull only for external nets.
Referenced by getRubbers().
getUnconnectedSlavePlugs()
Plugs Hurricane::Net::getUnconnectedSlavePlugs () const
Returns: the collection of unconnected plugs which have this net as master.
Remark:
Meaningfull only for external nets.
Referenced by getRubbers().
getIsGlobalFilter()
NetFilter Hurricane::Net::getIsGlobalFilter () [static]
Returns: the filter selecting global nets.
Referenced by getRubbers().
getIsExternalFilter()
NetFilter Hurricane::Net::getIsExternalFilter () [static]
Returns: the filter selecting external nets.
Referenced by getRubbers().
getIsInternalFilter()
NetFilter Hurricane::Net::getIsInternalFilter () [static]
Returns: the filter selecting internal nets.
Referenced by getRubbers().
getIsClockFilter()
NetFilter Hurricane::Net::getIsClockFilter () [static]
Returns: the filter selecting clock nets.
Referenced by getRubbers().
getIsSupplyFilter()
NetFilter Hurricane::Net::getIsSupplyFilter () [static]
Returns: the filter selecting supply nets.
Referenced by getRubbers().
isGlobal()
bool Hurricane::Net::isGlobal () const [inline]
Returns: true if the net is global else false.
Referenced by isSupply().
isExternal()
bool Hurricane::Net::isExternal () const [inline]
Returns: true if the net is external else false.
Referenced by isSupply().
isLogical()
bool Hurricane::Net::isLogical () const [inline]
Returns: true if the net is logical else false.
References Hurricane::Net::Type::LOGICAL.
isClock()
bool Hurricane::Net::isClock () const [inline]
Returns: true if the net is a clock else false.
References Hurricane::Net::Type::CLOCK, Hurricane::Net::Type::GROUND, and Hurricane::Net::Type::POWER.
isSupply()
bool Hurricane::Net::isSupply () const [inline]
Returns: true if the net is a supply else false.
References Hurricane::Net::Type::CLOCK, Hurricane::Net::Direction::ConnTristate, Hurricane::Net::Direction::ConnWiredOr, Hurricane::Net::Direction::DirIn, Hurricane::Net::Direction::DirOut, getClone(), getName(), Hurricane::Net::Type::GROUND, Hurricane::Net::Direction::IN, Hurricane::Net::Direction::INOUT, isExternal(), isGlobal(), Hurricane::Net::Type::LOGICAL, materialize(), merge(), Hurricane::Net::Direction::OUT, Hurricane::Net::Type::POWER, setArity(), setDirection(), setExternal(), setGlobal(), setName(), setPosition(), setType(), Hurricane::Net::Direction::TRANSCV, Hurricane::Net::Direction::TRISTATE, Hurricane::Net::Type::UNDEFINED, Hurricane::Net::Direction::UNDEFINED, unmaterialize(), Hurricane::Net::Direction::WOR_INOUT, and Hurricane::Net::Direction::WOR_OUT.
setName()
void Hurricane::Net::setName (Name name)
Allows to change net name.
Remark:
Throws an exception if the new name is empty, or if a net with same net already exists in the cell.
Referenced by isSupply().
setArity()
void Hurricane::Net::setArity (const Arity & arity)
Sets the signal arity to <arity>.
Referenced by isSupply().
setGlobal()
void Hurricane::Net::setGlobal (bool state)
Sets global signal status to <state>.
Referenced by isSupply().
setExternal()
void Hurricane::Net::setExternal (bool state)
Sets the external net status to <state>.
Remark:
This function will throw an exception if the net switches to internal and there is a plug refering to it.
Referenced by isSupply().
setType()
void Hurricane::Net::setType (const Type & type)
Sets the signal type of the net.
Referenced by isSupply().
setDirection()
void Hurricane::Net::setDirection (const Direction & direction)
Sets the signal direction of the net.
Referenced by isSupply().
setPosition()
void Hurricane::Net::setPosition (const Point & position)
Sets the X,Y location of the net. By default it is located at the coordinates origin of the cell (point 0,0).
Referenced by isSupply().
materialize()
void Hurricane::Net::materialize ()
Materializes all the rubbers and components of a net.
Referenced by isSupply().
unmaterialize()
void Hurricane::Net::unmaterialize ()
De-materializes all rubbers and the components of a net.
Referenced by isSupply().
merge()
void Hurricane::Net::merge (Net * net)
Merges the net <net> to the net <this> which keeps its characteristics (arity, global, external and direction).
Caution:
An exception is thrown if the <net> is null or equal to <this>, if the two nets don't belong to the same cell or if <net> is external and master net of a connected plug while net <this> is not external.
Remark:
All the rubbers and the components of the <net> (and also the plugs) become rubbers or components of the net <this>. Nevertheless if for a particular slave instance there was both a plug referencing the <net> and an other plug referencing <this>, the first is deleted to the advantage of the second, because a net can't have more than one plug for a given instance (the rings of the body hooks are then merged).
Remark:
Once the merger done the net <net> is definitively deleted. Its properties and those of its deleted plugs, if any, are lost (as well as the ones which could be attached to their occurences).
Referenced by isSupply().
getClone()
Net * Hurricane::Net::getClone (Cell * cloneCell)
Build a duplicate of net (<this>) inside a cloned Cell <cloneCell>. The connectivity (Plug) or components of the original net are not copied.
Remark:
It is likely that <cloneCell> is a copy of this net's onwer Cell, but it is not mandatory.
Referenced by isSupply().
The documentation for this class was generated from the following files:
Net.h
Net.dox