Hurricane Namespace Reference
The namespace dedicated to Hurricane.
Classes
class DebugSession
Enable/Disable trace information (API).
class Initializer
Register a static initialization function.
class JsonObject
Support for JSON export.
class JsonStack
JSON Parser Stack.
class Exception
Exception description (API)
class Error
Error description (API)
class Warning
Warning description (API)
class Interruption
Interruption description (API)
class GenericCollection
Generic Collection auto-pointer.
class SubTypeCollection
Applies a Type Filter to a Collection.
class SubSetCollection
Applies a Filter to a Collection.
class Collection
Collection description (API)
class ListCollection
Hurricane Collection wrapper around a std::list.
class MapCollection
Hurricane Collection wrapper around a std::map.
class SetCollection
Hurricane Collection wrapper around a std::set.
class VectorCollection
Hurricane Collection wrapper around a std::vector.
class Locator
Locator description (API)
class GenericLocator
Generic Locator auto-pointer.
class GenericFilter
Generic Filter auto-pointer.
class NotFilter
Filter negation.
class Filter
Filter description (API)
class Relation
Relation description (API)
class StandardRelation
StandardRelation description (API)
class Tabulation
Tabulation description (API)
class DbU
DataBase Unit managment (API).
class Point
Point description (API)
class Box
Box description (API)
class Interval
Interval description (API)
class Transformation
Transformation description (API)
class Name
Name description (API)
class DBo
DataBase object root class (API).
class DataBase
The whole DataBase (API).
class PhysicalRule
Define a rule for the technology (API).
class Technology
Technological rules description (API).
class Layer
Layer description (API)
class BasicLayer
BasicLayer description (API)
class RegularLayer
RegularLayer description (API)
class ViaLayer
ViaLayer description (API)
class ContactLayer
ContactLayer description (API)
class DiffusionLayer
DiffusionLayer description (API)
class TransistorLayer
TransistorLayer description (API)
class Library
Library description (API)
class Entity
Occurrenceable objects root class (API).
class Cell
The model (API).
class Net
Net description (API)
class HyperNet
HyperNet description (API)
class Go
Go description (API)
class Instance
Instance description (API)
class Component
Component description (API)
class Plug
Plug description (API)
class Contact
Contact description (API)
class Pin
Pin description (API)
class Segment
Segment description (API)
class Vertical
Vertical description (API)
class Horizontal
Horizontal description (API)
class Pad
Pad description (API)
class Polygon
Polygon description (API)
class Diagonal
Diagonal description (API)
class Rubber
Rubber description (API)
class RoutingPad
RoutingPad description (API)
class Quark
Quark description (API)
class Property
Property description (API)
class PrivateProperty
PrivateProperty description (API)
class StandardPrivateProperty
StandardPrivateProperty description (API)
class SharedProperty
SharedProperty description (API)
class StandardSharedProperty
StandardSharedProperty description (API)
class Hook
Hook description (API)
class Path
Path description (API)
class Occurrence
Occurrence description (API)
class QuadTree
QuadTree description (API)
class Slice
Slice description (API)
class Query
Query description (API)
class UpdateSession
UpdateSession description (API)
Typedefs
typedef GenericCollection< Cell * > Cells
typedef GenericLocator< Cell * > CellLocator
typedef GenericFilter< Cell * > CellFilter
 DBo Collection
typedef GenericCollection< DBo * > DBos
typedef GenericLocator< DBo * > DBoLocator
typedef GenericFilter< DBo * > DBoFilter
 Layer Collection
typedef GenericCollection< Layer * > Layers
typedef GenericLocator< Layer * > LayerLocator
typedef GenericFilter< Layer * > LayerFilter
 Library Collection
typedef GenericCollection< Library * > Libraries
typedef GenericLocator< Library * > LibraryLocator
typedef GenericFilter< Library * > LibraryFilter
 Entity Collection
typedef GenericCollection< Entity * > Entities
typedef GenericLocator< Entity * > EntityLocator
typedef GenericFilter< Entity * > EntityFilter
 Net Collection
typedef GenericCollection< Net * > Nets
typedef GenericLocator< Net * > NetLocator
typedef GenericFilter< Net * > NetFilter
 Go Collection
typedef GenericCollection< Go * > Gos
typedef GenericLocator< Go * > GoLocator
typedef GenericFilter< Go * > GoFilter
 Instance Collection
typedef GenericCollection< Instance * > Instances
typedef GenericLocator< Instance * > InstanceLocator
typedef GenericFilter< Instance * > InstanceFilter
 Component Collection
typedef GenericCollection< Component * > Components
typedef GenericLocator< Component * > ComponentLocator
typedef GenericFilter< Component * > ComponentFilter
 Plug Collection
typedef GenericCollection< Plug * > Plugs
typedef GenericLocator< Plug * > PlugLocator
typedef GenericFilter< Plug * > PlugFilter
 Contact Collection
typedef GenericCollection< Contact * > Contacts
typedef GenericLocator< Contact * > ContactLocator
typedef GenericFilter< Contact * > ContactFilter
 Segment Collection
typedef GenericCollection< Segment * > Segments
typedef GenericLocator< Segment * > SegmentLocator
typedef GenericFilter< Segment * > SegmentFilter
 Vertical Collection
typedef GenericCollection< Vertical * > Verticals
typedef GenericLocator< Vertical * > VerticalLocator
typedef GenericFilter< Vertical * > VerticalFilter
 Horizontal Collection
typedef GenericCollection< Horizontal * > Horizontals
typedef GenericLocator< Horizontal * > HorizontalLocator
typedef GenericFilter< Horizontal * > HorizontalFilter
 Pad Collection
typedef GenericCollection< Pad * > Pads
typedef GenericLocator< Pad * > PadLocator
typedef GenericFilter< Pad * > PadFilter
 Rubber Collection
typedef GenericCollection< Rubber * > Rubbers
typedef GenericLocator< Rubber * > RubberLocator
typedef GenericFilter< Rubber * > RubberFilter
 Property Collection
typedef GenericCollection< Property * > Properties
typedef GenericLocator< Property * > PropertyLocator
typedef GenericFilter< Property * > PropertyFilter
 Hook Collection
typedef GenericCollection< Hook * > Hooks
typedef GenericLocator< Hook * > HookLocator
typedef GenericFilter< Hook * > HookFilter
 Path Collection
typedef GenericCollection< Path > Pathes
typedef GenericLocator< Path > PathLocator
typedef GenericFilter< Path > PathFilter
 Occurrence Collection
typedef GenericCollection< Occurrence > Occurrences
typedef GenericLocator< Occurrence > OccurrenceLocator
typedef GenericFilter< Occurrence > OccurrenceFilter
 Slice Collection
typedef GenericCollection< Slice * > Slices
typedef GenericLocator< Slice * > SliceLocator
typedef GenericFilter< Slice * > SliceFilter
Functions
string demangle (const char *symbol)
string demangle (const type_info &info)
Detailed Description
The namespace dedicated to Hurricane.
Contains Almost Everything.
Almost everything is inside the Hurricane namespace.
Typedef Documentation
DBos
typedef GenericCollection< DBo * > Hurricane::DBos
Generic collection representing a set of data base objects.
DBoLocator
typedef GenericLocator< DBo * > Hurricane::DBoLocator
Generic locator for visiting a data base objects Collection.
DBoFilter
typedef GenericFilter< DBo * > Hurricane::DBoFilter
Filter to selecting a subset of data base objects matching some criteria.
Layers
Hurricane::Layers
Generic collection representing a set of layers.
LayerLocator
Hurricane::LayerLocator
Generic locator for traversing a collection of layers.
LayerFilter
Hurricane::LayerFilter
Generic filter allowing to select a subset of layers matching some criteria.
Libraries
Hurricane::Libraries
Generic collection representing a set of libraries.
LibraryLocator
Hurricane::LibraryLocator
Generic locator for traversing a collection of libraries.
LibraryFilter
Hurricane::LibraryFilter
Generic filter allowing to select a subset of libraries matching some criteria.
Entities
typedef GenericCollection< Entity * > Hurricane::Entities
Generic collection representing a set of data base objects.
EntityLocator
typedef GenericLocator< Entity * > Hurricane::EntityLocator
Generic locator for visiting a data base objects Collection.
EntityFilter
typedef GenericFilter< Entity * > Hurricane::EntityFilter
Filter to selecting a subset of data base objects matching some criteria.
Cells
typedef GenericCollection< Cell * > Hurricane::Cells
Generic collection representing a set of cell objects.
CellLocator
typedef GenericLocator< Cell * > Hurricane::CellLocator
Generic locator for visiting a cell objects Collection.
CellFilter
typedef GenericFilter< Cell * > Hurricane::CellFilter
Filter to selecting a subset of cell objects matching some criteria.
Nets
Hurricane::Nets
Generic collection representing a set of nets.
NetLocator
Hurricane::NetLocator
Generic locator for traversing a collection of nets.
NetFilter
Hurricane::NetFilter
Generic filter allowing to select a subset of nets matching some criteria.
Gos
Hurricane::Gos
Generic collection representing a set of graphic objects.
GoLocator
Hurricane::GoLocator
Generic locator for visiting a collection of graphic objects.
GoFilter
Hurricane::GoFilter
Filter to selecting a subset of graphic objects matching some criteria.
Instances
Hurricane::Instances
Generic collection representing a set of instances.
InstanceLocator
Hurricane::InstanceLocator
Generic locator for traversing a collection of instances.
InstanceFilter
Hurricane::InstanceFilter
Generic filter allowing to select a subset of instances matching some criteria.
Components
Hurricane::Components
Generic collection representing a set of components.
ComponentLocator
Hurricane::ComponentLocator
Generic locator for traversing a collection of components.
ComponentFilter
Hurricane::ComponentFilter
Generic filter for selecting a subset of components matching some criteria.
Plugs
Hurricane::Plugs
Generic collection representing a set of plugs.
PlugLocator
Hurricane::PlugLocator
Generic locator for traversing a collection of plugs.
PlugFilter
Hurricane::PlugFilter
Generic filter allowing to select a subset of plugs matching some criteria.
Contacts
Hurricane::Contacts
Generic collection representing a set of contacts.
ContactLocator
Hurricane::ContactLocator
Generic locator for traversing a collection of contacts.
ContactFilter
Hurricane::ContactFilter
Generic filter allowing to select a subset of contacts matching some criteria.
Segments
Hurricane::Segments
Generic collection representing a set of segments.
SegmentLocator
Hurricane::SegmentLocator
Generic locator for traversing a collection of segments.
SegmentFilter
Hurricane::SegmentFilter
Generic filter allowing to select a subset of segments matching some criteria.
Verticals
Hurricane::Verticals
Generic collection representing a set of vertical segments.
VerticalLocator
Hurricane::VerticalLocator
Generic locator for traversing a collection of vertical segments.
VerticalFilter
Hurricane::VerticalFilter
Generic filter allowing to select a subset of verticals matching some criteria.
Horizontals
Hurricane::Horizontals
Generic collection representing a set of horizontal segments.
HorizontalLocator
Hurricane::HorizontalLocator
Generic locator for traversing a collection of horizontal segments.
HorizontalFilter
Hurricane::HorizontalFilter
Generic filter allowing to select a subset of horizontals matching some criteria.
Pads
Hurricane::Pads
Generic collection representing a set of pads.
PadLocator
Hurricane::PadLocator
Generic locator for traversing a collection of pads.
PadFilter
Hurricane::PadFilter
Generic filter allowing to select a subset of pads matching some criteria.
Rubbers
Hurricane::Rubbers
Generic collection representing a set of rubbers.
RubberLocator
Hurricane::RubberLocator
Generic locator for traversing a collection of rubbers.
RubberFilter
Hurricane::RubberFilter
Generic filter allowing to select a subset of rubbers matching some criteria.
Properties
Hurricane::Properties
Generic collection representing a set of properties.
PropertyLocator
Hurricane::PropertyLocator
Generic locator for visiting a property collection.
PropertyFilter
Hurricane::PropertyFilter
Filter to selecting a subset of properties matching some criteria.
Hooks
Hurricane::Hooks
Collection representing a set of hooks.
HookLocator
Hurricane::HookLocator
Locator for traversing a collection of hooks.
HookFilter
Hurricane::HookFilter
Fiter for selecting a sub-set of hooks matching a given criteria.
Pathes
Hurricane::Pathes
Collection representing a set of pathes.
PathLocator
Hurricane::PathLocator
Locator for traversing a collection of pathes.
PathFilter
Hurricane::PathFilter
Filter for selecting a subset of pathes matching some criteria.
Occurrences
Hurricane::Occurrences
Collection representing a set of occurrences.
OccurrenceLocator
Hurricane::OccurrenceLocator
Locator for traversing a set of occurrences.
OccurrenceFilter
Hurricane::OccurrenceFilter
Filter for selecting a subset of occurrences matching some criteria.
Slices
Hurricane::Slices
Collection representing a set of slices.
SliceLocator
Hurricane::SliceLocator
Locator for traversing a collection of slices.
SliceFilter
Hurricane::SliceFilter
Filter for selecting a subset of slices which match a given criteria.
Function Documentation
demangle() [1/2]
string Hurricane::demangle (const char * symbol)
Translate (demangle) a symbol from C++ (gnu-v3) internal format into a human readable string.
Referenced by Hurricane::JsonStack::as(), demangle(), Hurricane::JsonStack::push_back(), and Hurricane::JsonStack::rhas().
demangle() [2/2]
string Hurricane::demangle (const type_info & info) [inline]
Parameters
info a type_info structure as returned by typeid().
Translate (demangle) a symbol from C++ (gnu-v3) internal format into a human readable string.
References demangle().