
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY o4_x4 IS
PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
);
END o4_x4;

ARCHITECTURE RTL OF o4_x4 IS
BEGIN
  q <= (((i0 OR i1) OR i2) OR i3);
END RTL;
