
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY xr2_x1 IS
PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
);
END xr2_x1;

ARCHITECTURE RTL OF xr2_x1 IS
BEGIN
  q <= (i0 XOR i1);
END RTL;
