
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY na2_x1 IS
PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
);
END na2_x1;

ARCHITECTURE RTL OF na2_x1 IS
BEGIN
  nq <= NOT((i0 AND i1));
END RTL;
