
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY na4_x4 IS
PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
);
END na4_x4;

ARCHITECTURE RTL OF na4_x4 IS
BEGIN
  nq <= NOT((((i0 AND i1) AND i2) AND i3));
END RTL;
