
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY nmx2_x4 IS
PORT(
  cmd	: IN STD_LOGIC;
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
);
END nmx2_x4;

ARCHITECTURE RTL OF nmx2_x4 IS
BEGIN
  nq <= NOT(((i0 AND NOT(cmd)) OR (i1 AND cmd)));
END RTL;
