
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY nxr2_x4 IS
PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
);
END nxr2_x4;

ARCHITECTURE RTL OF nxr2_x4 IS
BEGIN
  nq <= NOT((i0 XOR i1));
END RTL;
