
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY one_x0 IS
PORT(
  q	: OUT STD_LOGIC
);
END one_x0;

ARCHITECTURE RTL OF one_x0 IS
BEGIN
  q <= '1';
END RTL;
