.TH "katabatic Directory Reference" 3 "Thu Mar 19 2020" "Version 1.0" "Katabatic - Routing Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
katabatic Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAutoContact\&.h\fP"
.br
.ti -1c
.RI "file \fBAutoContactHTee\&.h\fP"
.br
.ti -1c
.RI "file \fBAutoContactTerminal\&.h\fP"
.br
.ti -1c
.RI "file \fBAutoContactTurn\&.h\fP"
.br
.ti -1c
.RI "file \fBAutoContactVTee\&.h\fP"
.br
.ti -1c
.RI "file \fBAutoHorizontal\&.h\fP"
.br
.ti -1c
.RI "file \fBAutoSegment\&.h\fP"
.br
.ti -1c
.RI "file \fBAutoSegments\&.h\fP"
.br
.ti -1c
.RI "file \fBAutoVertical\&.h\fP"
.br
.ti -1c
.RI "file \fBChipTools\&.h\fP"
.br
.ti -1c
.RI "file \fBConstants\&.h\fP"
.br
.ti -1c
.RI "file \fBGCell\&.h\fP"
.br
.ti -1c
.RI "file \fBGCellGrid\&.h\fP"
.br
.ti -1c
.RI "file \fBGCells\&.h\fP"
.br
.ti -1c
.RI "file \fBGrid\&.h\fP"
.br
.ti -1c
.RI "file \fBKatabaticEngine\&.h\fP"
.br
.ti -1c
.RI "file \fBObserver\&.h\fP"
.br
.ti -1c
.RI "file \fBSession\&.h\fP"
.br
.in -1c
