.TH "GCell::CompareByDensity" 3 "Sun Nov 21 2021" "Version 1.0" "Katabatic - Routing Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GCell::CompareByDensity \- \fBGCell\fP Density Comparison Functor\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits binary_function< GCell *, GCell *, bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompareByDensity\fP (unsigned int depth)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGCell\fP Density Comparison Functor\&. 

A comparison functor for \fBGCell\fP, compare by density on layer \fCdepth\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCompareByDensity\fP (unsigned int depth)"
Build a density comparator for GCells on layer \fCdepth\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Katabatic - Routing Toolbox from the source code\&.
