.TH "grpSynthHierarchy" 3 "Thu Nov 12 2020" "Version 1.0" "Katabatic - Routing Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grpSynthHierarchy \- Simplificated class hierarchy\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Simplificated class hierarchy\&. 

 
.SH "Author"
.PP 
Generated automatically by Doxygen for Katabatic - Routing Toolbox from the source code\&.
