.TH "AutoSegments_OnContact" 3 "Sun Nov 21 2021" "Version 1.0" "Katabatic - Routing Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoSegments_OnContact \- All \fBAutoSegment\fP anchored on a Contact\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCollection< Type >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutoSegments_OnContact\fP (\fBAutoSegment\fP *master, \fBContact\fP *contact)"
.br
.ti -1c
.RI "\fBAutoSegments_OnContact\fP (const \fBAutoSegments_OnContact\fP &)"
.br
.ti -1c
.RI "virtual \fBAutoSegmentHC\fP * \fBgetClone\fP () const"
.br
.ti -1c
.RI "virtual \fBAutoSegmentHL\fP * \fBgetLocator\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
All \fBAutoSegment\fP anchored on a Contact\&. 

All \fBAutoSegment\fP Beginning from an \fBAutoContact\fP\&.
.PP
A Collection to iterate over all the \fBAutoSegment\fP anchored on \fCcontact\fP\&. If supplied, the \fBAutoSegment\fP \fCmaster\fP will be excluded from the list\&.
.PP
\fBRemark: If a Hurricane::Segment is anchored on the \fCcontact\fP, but is not\fP
.RS 4
associated to an \fBAutoSegment\fP, it will be silently skipped\&.
.RE
.PP
A Collection to iterate over all the \fBAutoSegment\fP that begin from \fBAutoContact\fP\&. As AutoSegments are kept orienteds (source anchor must be lower than target), selecting source anchored AutoSegments implies that they are starting from this \fBAutoContact\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAutoSegments_OnContact\fP (\fBAutoSegment\fP * master, \fBContact\fP * contact)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fImaster\fP Exclude this \fBAutoSegment\fP from the Collection\&. 
.br
\fIcontact\fP The Hurricane Contact over which to iterate\&.
.RE
.PP
Construct a Collection of all the \fBAutoSegment\fP anchored on \fCcontact\fP\&.
.PP
Create the collection of all AutoSegments direcly anchored on \fCcontact\fP, with exclusion of \fCmaster\fP\&. 
.SS "\fBAutoSegments_OnContact\fP (const \fBAutoSegments_OnContact\fP & segments)\fC [inline]\fP"
Copy constructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBAutoSegmentHC\fP * getClone () const\fC [virtual]\fP"
\fBReturns:\fP A deep copy of the Collection\&. 
.PP
Implements \fBCollection< Type >\fP\&.
.SS "\fBAutoSegmentHC\fP * getLocator () const\fC [virtual]\fP"
\fBReturns:\fP A deep copy of the Collection Locator\&. 
.PP
Implements \fBCollection< Type >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Katabatic - Routing Toolbox from the source code\&.
