.TH "BaseGrid::Axis" 3 "Mon Apr 27 2020" "Version 1.0" "Katabatic - Routing Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseGrid::Axis \- Graduations on a \fBBaseGrid\fP \fBAxis\fP (H or V)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddGraduation\fP (\fBDbU::Unit\fP)"
.br
.ti -1c
.RI "void \fBsort\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetSize\fP () const"
.br
.ti -1c
.RI "unsigned int \fBgetGraduationNumber\fP (\fBDbU::Unit\fP pos, bool &onGraduation) const"
.br
.ti -1c
.RI "const \fBDbU::Unit\fP & \fBoperator[]\fP (unsigned int i) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graduations on a \fBBaseGrid\fP \fBAxis\fP (H or V)\&. 

Describe the list of graduations on either X or Y axis of a \fBBaseGrid\fP\&. Graduations correspond to cut lines and may not be evenly spaced\&.
.PP
Graduations are internally stored into a vector that needs to be sorted whenever new graduations are added (\fBBaseGrid::Axis::sort()\fP)\&. 
.SH "Member Function Documentation"
.PP 
.SS "void addGraduation (\fBDbU::Unit\fP pos)\fC [inline]\fP"
Adds a new graduation\&. After adding new graduations, do not forget to perform a sort\&. 
.PP
Referenced by GCellGrid::_postCreate()\&.
.SS "void sort ()"
Re-order the graduations after an addition\&. 
.PP
Referenced by GCellGrid::_postCreate()\&.
.SS "size_t getSize () const\fC [inline]\fP"
\fBReturns:\fP The number of graduations on the axis\&. 
.PP
Referenced by GCellGrid::_postCreate()\&.
.SS "\fBDbU::Unit\fP getGraduationNumber (\fBDbU::Unit\fP pos, bool & onGraduation) const"
\fBReturns:\fP The index of the graduation which is immediatly inferior or equal to \fCpos\fP\&. In case of strict equality, \fConGraduation\fP is set to \fBtrue\fP\&. 
.SS "\fBDbU::Unit\fP operator[] (unsigned int index) const\fC [inline]\fP"
\fBReturns:\fP The graduation at \fCindex\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Katabatic - Routing Toolbox from the source code\&.
