.TH "GCell::CompareByIndex" 3 "Sun Nov 21 2021" "Version 1.0" "Katabatic - Routing Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GCell::CompareByIndex \- \fBGCell\fP Index Comparison Functor\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits binary_function< const GCell *, const GCell *, bool >\&.
.SH "Detailed Description"
.PP 
\fBGCell\fP Index Comparison Functor\&. 

A comparison functor for \fBGCell\fP, compare by \fCindex\fP (the linear index in the \fBGCellGrid\fP vector\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Katabatic - Routing Toolbox from the source code\&.
