.TH "BaseObserver" 3 "Fri Oct 1 2021" "Version 1.0" "Katabatic - Routing Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseObserver \- \fBObserver\fP Design Pattern, \fBObserver\fP part\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObserver< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBnotify\fP (unsigned int flags)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBObserver\fP Design Pattern, \fBObserver\fP part\&. 

This class is used as a non-template base class for the templatized \fBObserver\fP one\&. It is used to avoid propagating template to the whole \fBObservable\fP class\&. It only contains the \fBObserver::notify()\fP virtual method\&. 
.SH "Member Function Documentation"
.PP 
.SS "void notify (unsigned int flags)\fC [virtual]\fP"
The method which will be called whenever a change occurs on the \fBObservable\fP\&. 
.PP
Referenced by Observable::notify()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Katabatic - Routing Toolbox from the source code\&.
