.TH "python Directory Reference" 3 "Thu Mar 19 2020" "Version 1.0" "Oroshi - Analog Devices Layout" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCapacitorMatrix\&.py\fP"
.br
.ti -1c
.RI "file \fBCapacitorRouted\&.py\fP"
.br
.ti -1c
.RI "file \fBCapacitorUnit\&.py\fP"
.br
.ti -1c
.RI "file \fBCapacitorVRTracks\&.py\fP"
.br
.ti -1c
.RI "file \fBStack\&.py\fP"
.br
.ti -1c
.RI "file \fBWIP_CSP\&.py\fP"
.br
.ti -1c
.RI "file \fBWIP_DP\&.py\fP"
.br
.ti -1c
.RI "file \fBWIP_Transistor\&.py\fP"
.br
.in -1c
