PROJECT(PARSEDRIVESPICE)

CMAKE_MINIMUM_REQUIRED(VERSION 2.4.0)

SET(CMAKE_MODULE_PATH "$ENV{VLSISAPD_USER_TOP}/share/cmake/Modules"
                      "$ENV{VLSISAPD_TOP}/share/cmake/Modules"
   )

FIND_PACKAGE(VLSISAPD REQUIRED)

IF(SPICE_FOUND)
    INCLUDE_DIRECTORIES(${SPICE_INCLUDE_DIR})
#    ADD_EXECUTABLE(driveSpice driveSpice.cpp)
    ADD_EXECUTABLE(parseSpice parseSpice.cpp)
#    TARGET_LINK_LIBRARIES(driveOpenChams ${SPICE_LIBRARY})
    TARGET_LINK_LIBRARIES(parseOpenChams ${SPICE_LIBRARY})
ENDIF(SPICE_FOUND)
