
FROM debian10.coriolis

# Cannot clone directly from LibreSOC repository as I need my
# ssh key that I cannot forward to the docker build process.
#
# git clone ssh://gitolite3@libre-riscv.org:922/soclayout.git 

COPY ./root/soclayout /root/coriolis-2.x/src/soclayout
RUN  cd /root/coriolis-2.x/src/soclayout \
 &&  git checkout 75e03eb

