AutoContactVTee Class Reference
AutoContact V-Tee (one H, two V)
Public Member Functions
virtual AutoSegment * getOpposite (const AutoSegment *) const
virtual AutoSegment * getPerpandicular (const AutoSegment *) const
virtual AutoSegment * getSegment (unsigned int) const
virtual void updateGeometry ()
virtual void updateTopology ()
Static Public Member Functions
static AutoContactVTee * create (GCell *, Net *, const Layer *)
Additional Inherited Members
Detailed Description
AutoContact V-Tee (one H, two V)
AutoContact to build a vertical tee (two V, one H).
Member Function Documentation
create()
AutoContactVTee * create (GCell * gcell, Net * net, const Layer * layer) [static]
Parameters
gcell The GCell into which create the AutoContact.
net The Net to which this AutoContact belongs.
layer The Layer of the AutoContact.
Returns
The created AutoContactVTee.
Create a new AutoContactVTee.
References Katabatic::CntInCreationStage, Katabatic::CntVTee, and Contact::create().
getOpposite()
AutoSegment * getOpposite (const AutoSegment * reference) const [virtual]
Returns: The other AutoSegment the same direction as reference, this is only meaningful on AutoContactHTee or AutoContactVTee. If there is no opposite, NULL is returned.
Implements AutoContact.
getPerpandicular()
AutoSegment * getPerpandicular (const AutoSegment * reference) const [virtual]
Returns: The AutoSegment in the perpandicular direction to reference, this is only meaningful on AutoContacTurn. It there is no unique perpandicular, NULL is returned.
Implements AutoContact.
getSegment()
AutoSegment * getSegment (unsigned int index) const [virtual]
Returns: The nth anchored AutoSegment. The index is significant:
0 : first horizontal (h1).
1 : second horizontal (h2).
2 : first vertical (b1).
3 : second vertical (b2).
Not all the indexes are filled for every AutoContact. For example Turn have h1 and b1, and HTee have h1, h2 and v1.
Implements AutoContact.
References AutoContact::_getTopology(), AutoContact::base(), DebugSession::close(), Katabatic::CntBadTopology, Katabatic::CntInvalidatedCache, AutoSegment::getDirection(), AutoContact::getNet(), AutoSegment::getY(), AutoSegment::invalidate(), AutoSegment::isCreated(), AutoSegment::isInvalidated(), Katabatic::KbHorizontal, Katabatic::KbPropagate, Katabatic::KbVertical, Session::lookup(), DebugSession::open(), and AutoContact::showTopologyError().
updateGeometry()
void updateGeometry () [virtual]
Compute the new position of the AutoContact based on the AutoSegment positions. The Session mechanism ensure that all AutoSegment are set into their final positions before calling this updator.
Implements AutoContact.
References AutoContact::base(), DebugSession::close(), Katabatic::CntInvalidated, AutoContact::getNet(), AutoContact::getX(), AutoContact::getY(), AutoContact::hasBadTopology(), Go::invalidate(), AutoContact::isInvalidatedCache(), DebugSession::open(), AutoContact::setX(), and AutoContact::setY().
updateTopology()
void updateTopology () [virtual]
Restore the topology (i.e. connexity) of the contact after any number of connected segments has changed layer (at least one, up to three).
For a detailed explanation, see AutoContactHTee::updateTopology() and sawp horizontal & vertical...
Implements AutoContact.
References DebugSession::close(), Katabatic::CntBadTopology, RoutingGauge::getContactLayer(), AutoContact::getLayer(), RoutingGauge::getLayerDepth(), AutoContact::getNet(), Session::getRoutingGauge(), RoutingGauge::getRoutingLayer(), AutoContact::hasBadTopology(), AutoSegment::invalidate(), AutoContact::isInvalidatedCache(), AutoSegment::makeDogleg(), DebugSession::open(), AutoContact::setLayer(), and AutoContact::showTopologyError().
The documentation for this class was generated from the following files:
AutoContactVTee.h
AutoContactVTee.cpp
AutoContactVTee.dox