PROJECT(DRIVEAGDS)

CMAKE_MINIMUM_REQUIRED(VERSION 2.4.0)

SET(CMAKE_MODULE_PATH "$ENV{VLSISAPD_USER_TOP}/share/cmake/Modules"
                      "$ENV{VLSISAPD_TOP}/share/cmake/Modules" 
   )

FIND_PACKAGE(VLSISAPD REQUIRED)

IF(AGDS_FOUND)
    INCLUDE_DIRECTORIES ( ${AGDS_INCLUDE_DIR} )
    ADD_EXECUTABLE ( driveAgds driveAgds.cpp )
    TARGET_LINK_LIBRARIES ( driveAgds ${AGDS_LIBRARY} )
ENDIF(AGDS_FOUND)
